# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\x12\x04grpc\"\x10\n\x0eMyEmptyMessage\"*\n\tMyMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2r\n\x06Server\x12\x35\n\nChatStream\x12\x14.grpc.MyEmptyMessage\x1a\x0f.grpc.MyMessage0\x01\x12\x31\n\x08SendNote\x12\x0f.grpc.MyMessage\x1a\x14.grpc.MyEmptyMessageb\x06proto3'
)




_MYEMPTYMESSAGE = _descriptor.Descriptor(
  name='MyEmptyMessage',
  full_name='grpc.MyEmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=36,
)


_MYMESSAGE = _descriptor.Descriptor(
  name='MyMessage',
  full_name='grpc.MyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.MyMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.MyMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['MyEmptyMessage'] = _MYEMPTYMESSAGE
DESCRIPTOR.message_types_by_name['MyMessage'] = _MYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyEmptyMessage = _reflection.GeneratedProtocolMessageType('MyEmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _MYEMPTYMESSAGE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.MyEmptyMessage)
  })
_sym_db.RegisterMessage(MyEmptyMessage)

MyMessage = _reflection.GeneratedProtocolMessageType('MyMessage', (_message.Message,), {
  'DESCRIPTOR' : _MYMESSAGE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.MyMessage)
  })
_sym_db.RegisterMessage(MyMessage)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='grpc.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=82,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='grpc.Server.ChatStream',
    index=0,
    containing_service=None,
    input_type=_MYEMPTYMESSAGE,
    output_type=_MYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendNote',
    full_name='grpc.Server.SendNote',
    index=1,
    containing_service=None,
    input_type=_MYMESSAGE,
    output_type=_MYEMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
